
name: Java CI/CD 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Install Dependencies
      run: npm install
      env:
          CI: true

    - name: Build Project
      run: npm run build
      env:
          CI: true
  

      
 
