
name: Java CI/CD 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
       command: mkdir /usr/testfile
       host: ${{ secrets.TX_URL }}
       username: ${{ secrets.TX_USER }}
       password: ${{ secrets.TX_PASSWORD }}
       port: ${{ secrets.TX_PORT }}

      
 
